#!/bin/bash

set -ouex pipefail

echo "-- TyrianOS Administrator Reset Tool"

echo "-- Flag specified: $TART_FLAG"

full_reset() {
	echo "-- Save all of your important files to external partitions, this action will FULLY and IRREVERSIBLY get rid of your home folders and data under /home/"
	echo "-- Make sure to keep your device plugged in, to prevent any interruption."
	echo "-- Just in case, make sure to keep it connected to the internet as well."
	read -p "-- This option will uninstall ALL packages and delete ALL users irreversibly. Are you really sure you want to do this? (y/n) " OPT
	case $OPT in
		Y|y)
			echo "Not ready at all"
		;;
		*)
			echo "-- TyrianOS System Reset Cancelled"
			exit 1
		;;
	esac
}

full_reset.confirmed() {
	killall plasmashell || true
	echo "-- Cleaning up mutations..."
	rpm-ostree cleanup -m
	echo "-- Aggressively deleting all users, even if still logged in... (We're restarting, this will not matter.)"
	for u in $(awk -F: '$3 >= 1000 {print $1}' /etc/passwd); do userdel -f -r "$u"; done || echo "Failure on removing users using userdel!?"
	rm -rfv /home/* || true # in case users have been deleted but chose to keep their data
	rm -rfv /var/mail/*	 || true # in case users have been deleted but chose to keep their data
	echo "-- Wiping /etc (while preserving machine-id, hostname, fstab and crypttab.)"
	find /etc -mindepth 1 -maxdepth 1 ! -name 'machine-id' ! -name 'hostname' ! -name 'fstab' ! -name 'crypttab' -exec rm -rf {} +
	echo "-- Recreating /etc"
	cp -rTv /usr/etc /etc
	echo "-- Determining next boot's fate (Enabling initial setup)"
	systemctl enable initial-setup
	echo "-- To fully finish, TyrianOS will reboot in 10 seconds."
	sleep 9
	echo "-- Goodbye."
	sleep 1;reboot
}


case $TART_FLAG in
	C)
		full_reset
	;;
	*)
		echo "-- No matching flag. Quitting..."
		exit 1
	;;
esac
