set allow-duplicate-recipes := true
set ignore-comments := true

_default:
	#!/usr/bin/bash
	source /usr/lib/tyrianos/cli/colorvars.sh
	echo "TyrianOS Developer Tools"
	/usr/bin/tydev --list --list-heading $'commands:\n' --list-prefix $' - '
	
import "/usr/share/tyrianos/just/10-tempinstall.just"
